### ISSUE TITLE
Please add an readme.md!

### ISSUE THREAD

**Issue by byCRXHIT** [Developer-Dungeon-Studio/Ticketer#1]
Open-source is always a great idea, aslong someone is able to understand and run it.

I found it out by myself but it took like an hour to get it.

Making an simple ReadMe with a step by step list isn't that hard.
Even better would be by linking a video on how to use it.
After all it just makes the job for alot people much easier.

It would also be great to mention that it needs at least NodeJS Version 16 to run.

It also took me a while to find out the web server is localhost:7080

**Comment by mezotv** [comment]
Hey thanks for your feedback. Im gonna add a readme today and maybe record a Video on howvto setup the bot and use it!

**Comment by mezotv** [comment]
If you want to help us improve ticketer you can join our support server! https://discord.gg/KfBkKKydfg

**Comment by byCRXHIT** [comment]
Thanks! Great to hear that!
